version: '3'

services:
  app-service:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: 'app-container'
    tty: true
    ports:
      - '80:80'
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - the-sidea-network

networks:
  the-sidea-network:
    driver: bridge
